# LANGUAGE message translation file for plpython
# Copyright (C) 2018 PostgreSQL Global Development Group
# This file is distributed under the same license as the plpython (PostgreSQL) package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2018.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: plpython (PostgreSQL) 11\n"
"Report-Msgid-Bugs-To: pgsql-bugs@postgresql.org\n"
"POT-Creation-Date: 2018-04-22 12:08+0000\n"
"PO-Revision-Date: 2018-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=CHARSET\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=INTEGER; plural=EXPRESSION;\n"

#: plpy_cursorobject.c:101
#, c-format
msgid "plpy.cursor expected a query or a plan"
msgstr ""

#: plpy_cursorobject.c:184
#, c-format
msgid "plpy.cursor takes a sequence as its second argument"
msgstr ""

#: plpy_cursorobject.c:200 plpy_spi.c:211
#, c-format
msgid "could not execute plan"
msgstr ""

#: plpy_cursorobject.c:203 plpy_spi.c:214
#, c-format
msgid "Expected sequence of %d argument, got %d: %s"
msgid_plural "Expected sequence of %d arguments, got %d: %s"
msgstr[0] ""
msgstr[1] ""

#: plpy_cursorobject.c:352
#, c-format
msgid "iterating a closed cursor"
msgstr ""

#: plpy_cursorobject.c:360 plpy_cursorobject.c:426
#, c-format
msgid "iterating a cursor in an aborted subtransaction"
msgstr ""

#: plpy_cursorobject.c:418
#, c-format
msgid "fetch from a closed cursor"
msgstr ""

#: plpy_cursorobject.c:461 plpy_spi.c:409
#, c-format
msgid "query result has too many rows to fit in a Python list"
msgstr ""

#: plpy_cursorobject.c:512
#, c-format
msgid "closing a cursor in an aborted subtransaction"
msgstr ""

#: plpy_elog.c:127 plpy_elog.c:128 plpy_plpymodule.c:559
#, c-format
msgid "%s"
msgstr ""

#: plpy_exec.c:142
#, c-format
msgid "unsupported set function return mode"
msgstr ""

#: plpy_exec.c:143
#, c-format
msgid "PL/Python set-returning functions only support returning one value per call."
msgstr ""

#: plpy_exec.c:156
#, c-format
msgid "returned object cannot be iterated"
msgstr ""

#: plpy_exec.c:157
#, c-format
msgid "PL/Python set-returning functions must return an iterable object."
msgstr ""

#: plpy_exec.c:171
#, c-format
msgid "error fetching next item from iterator"
msgstr ""

#: plpy_exec.c:214
#, c-format
msgid "PL/Python procedure did not return None"
msgstr ""

#: plpy_exec.c:218
#, c-format
msgid "PL/Python function with return type \"void\" did not return None"
msgstr ""

#: plpy_exec.c:374 plpy_exec.c:400
#, c-format
msgid "unexpected return value from trigger procedure"
msgstr ""

#: plpy_exec.c:375
#, c-format
msgid "Expected None or a string."
msgstr ""

#: plpy_exec.c:390
#, c-format
msgid "PL/Python trigger function returned \"MODIFY\" in a DELETE trigger -- ignored"
msgstr ""

#: plpy_exec.c:401
#, c-format
msgid "Expected None, \"OK\", \"SKIP\", or \"MODIFY\"."
msgstr ""

#: plpy_exec.c:451
#, c-format
msgid "PyList_SetItem() failed, while setting up arguments"
msgstr ""

#: plpy_exec.c:455
#, c-format
msgid "PyDict_SetItemString() failed, while setting up arguments"
msgstr ""

#: plpy_exec.c:467
#, c-format
msgid "function returning record called in context that cannot accept type record"
msgstr ""

#: plpy_exec.c:684
#, c-format
msgid "while creating return value"
msgstr ""

#: plpy_exec.c:909
#, c-format
msgid "TD[\"new\"] deleted, cannot modify row"
msgstr ""

#: plpy_exec.c:914
#, c-format
msgid "TD[\"new\"] is not a dictionary"
msgstr ""

#: plpy_exec.c:941
#, c-format
msgid "TD[\"new\"] dictionary key at ordinal position %d is not a string"
msgstr ""

#: plpy_exec.c:948
#, c-format
msgid "key \"%s\" found in TD[\"new\"] does not exist as a column in the triggering row"
msgstr ""

#: plpy_exec.c:953
#, c-format
msgid "cannot set system attribute \"%s\""
msgstr ""

#: plpy_exec.c:1011
#, c-format
msgid "while modifying trigger row"
msgstr ""

#: plpy_exec.c:1072
#, c-format
msgid "forcibly aborting a subtransaction that has not been exited"
msgstr ""

#: plpy_main.c:125
#, c-format
msgid "multiple Python libraries are present in session"
msgstr ""

#: plpy_main.c:126
#, c-format
msgid "Only one Python major version can be used in one session."
msgstr ""

#: plpy_main.c:142
#, c-format
msgid "untrapped error in initialization"
msgstr ""

#: plpy_main.c:165
#, c-format
msgid "could not import \"__main__\" module"
msgstr ""

#: plpy_main.c:174
#, c-format
msgid "could not initialize globals"
msgstr ""

#: plpy_main.c:399
#, c-format
msgid "PL/Python procedure \"%s\""
msgstr ""

#: plpy_main.c:402
#, c-format
msgid "PL/Python function \"%s\""
msgstr ""

#: plpy_main.c:410
#, c-format
msgid "PL/Python anonymous code block"
msgstr ""

#: plpy_plpymodule.c:192 plpy_plpymodule.c:195
#, c-format
msgid "could not import \"plpy\" module"
msgstr ""

#: plpy_plpymodule.c:210
#, c-format
msgid "could not create the spiexceptions module"
msgstr ""

#: plpy_plpymodule.c:218
#, c-format
msgid "could not add the spiexceptions module"
msgstr ""

#: plpy_plpymodule.c:286
#, c-format
msgid "could not generate SPI exceptions"
msgstr ""

#: plpy_plpymodule.c:454
#, c-format
msgid "could not unpack arguments in plpy.elog"
msgstr ""

#: plpy_plpymodule.c:463
msgid "could not parse error message in plpy.elog"
msgstr ""

#: plpy_plpymodule.c:480
#, c-format
msgid "argument 'message' given by name and position"
msgstr ""

#: plpy_plpymodule.c:507
#, c-format
msgid "'%s' is an invalid keyword argument for this function"
msgstr ""

#: plpy_plpymodule.c:518 plpy_plpymodule.c:524
#, c-format
msgid "invalid SQLSTATE code"
msgstr ""

#: plpy_procedure.c:230
#, c-format
msgid "trigger functions can only be called as triggers"
msgstr ""

#: plpy_procedure.c:234
#, c-format
msgid "PL/Python functions cannot return type %s"
msgstr ""

#: plpy_procedure.c:312
#, c-format
msgid "PL/Python functions cannot accept type %s"
msgstr ""

#: plpy_procedure.c:402
#, c-format
msgid "could not compile PL/Python function \"%s\""
msgstr ""

#: plpy_procedure.c:405
#, c-format
msgid "could not compile anonymous PL/Python code block"
msgstr ""

#: plpy_resultobject.c:150 plpy_resultobject.c:176 plpy_resultobject.c:202
#, c-format
msgid "command did not produce a result set"
msgstr ""

#: plpy_spi.c:60
#, c-format
msgid "second argument of plpy.prepare must be a sequence"
msgstr ""

#: plpy_spi.c:104
#, c-format
msgid "plpy.prepare: type name at ordinal position %d is not a string"
msgstr ""

#: plpy_spi.c:176
#, c-format
msgid "plpy.execute expected a query or a plan"
msgstr ""

#: plpy_spi.c:195
#, c-format
msgid "plpy.execute takes a sequence as its second argument"
msgstr ""

#: plpy_spi.c:305
#, c-format
msgid "SPI_execute_plan failed: %s"
msgstr ""

#: plpy_spi.c:347
#, c-format
msgid "SPI_execute failed: %s"
msgstr ""

#: plpy_subxactobject.c:122
#, c-format
msgid "this subtransaction has already been entered"
msgstr ""

#: plpy_subxactobject.c:128 plpy_subxactobject.c:186
#, c-format
msgid "this subtransaction has already been exited"
msgstr ""

#: plpy_subxactobject.c:180
#, c-format
msgid "this subtransaction has not been entered"
msgstr ""

#: plpy_subxactobject.c:192
#, c-format
msgid "there is no subtransaction to exit from"
msgstr ""

#: plpy_typeio.c:591
#, c-format
msgid "could not import a module for Decimal constructor"
msgstr ""

#: plpy_typeio.c:595
#, c-format
msgid "no Decimal attribute in module"
msgstr ""

#: plpy_typeio.c:601
#, c-format
msgid "conversion from numeric to Decimal failed"
msgstr ""

#: plpy_typeio.c:908
#, c-format
msgid "could not create bytes representation of Python object"
msgstr ""

#: plpy_typeio.c:1056
#, c-format
msgid "could not create string representation of Python object"
msgstr ""

#: plpy_typeio.c:1067
#, c-format
msgid "could not convert Python object into cstring: Python string representation appears to contain null bytes"
msgstr ""

#: plpy_typeio.c:1176
#, c-format
msgid "number of array dimensions exceeds the maximum allowed (%d)"
msgstr ""

#: plpy_typeio.c:1180
#, c-format
msgid "could not determine sequence length for function return value"
msgstr ""

#: plpy_typeio.c:1183 plpy_typeio.c:1187
#, c-format
msgid "array size exceeds the maximum allowed"
msgstr ""

#: plpy_typeio.c:1213
#, c-format
msgid "return value of function with array return type is not a Python sequence"
msgstr ""

#: plpy_typeio.c:1259
#, c-format
msgid "wrong length of inner sequence: has length %d, but %d was expected"
msgstr ""

#: plpy_typeio.c:1261
#, c-format
msgid "To construct a multidimensional array, the inner sequences must all have the same length."
msgstr ""

#: plpy_typeio.c:1340
#, c-format
msgid "malformed record literal: \"%s\""
msgstr ""

#: plpy_typeio.c:1341
#, c-format
msgid "Missing left parenthesis."
msgstr ""

#: plpy_typeio.c:1342 plpy_typeio.c:1543
#, c-format
msgid "To return a composite type in an array, return the composite type as a Python tuple, e.g., \"[('foo',)]\"."
msgstr ""

#: plpy_typeio.c:1389
#, c-format
msgid "key \"%s\" not found in mapping"
msgstr ""

#: plpy_typeio.c:1390
#, c-format
msgid "To return null in a column, add the value None to the mapping with the key named after the column."
msgstr ""

#: plpy_typeio.c:1443
#, c-format
msgid "length of returned sequence did not match number of columns in row"
msgstr ""

#: plpy_typeio.c:1541
#, c-format
msgid "attribute \"%s\" does not exist in Python object"
msgstr ""

#: plpy_typeio.c:1544
#, c-format
msgid "To return null in a column, let the returned object have an attribute named after column with value None."
msgstr ""

#: plpy_util.c:35
#, c-format
msgid "could not convert Python Unicode object to bytes"
msgstr ""

#: plpy_util.c:41
#, c-format
msgid "could not extract bytes from encoded string"
msgstr ""
